### ISSUE TITLE
request header content was not present 

### ISSUE THREAD

**Issue by pilsna** [CTimmerman/nicescroll-vs-amp#1]
Hi,

Did you ever find an explanation for this problem?
Is it an IE11 bug or a Windows bug related to PlayReady?
I'm having the same error in relation to a PlayReady server.

/Nils

**Comment by CTimmerman** [comment]
Nope. I ended up checking all the packages and removing nicescroll.

**Comment by pilsna** [comment]
ok, thanks for answering!
